<#macro sortActions>

  <div class="col m-5">
      <a href="#" class="nav-link link-dark dropdown-toggle p-0" type="button" id="dropdownOptions"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort
      </a>
      <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="/sort/low-price">Low price first</a></li>
          <li><a class="dropdown-item" href="/sort/high-price">High price first</a></li>
      </ul>
  </div>

</#macro>